# Generated by Django 3.2.11 on 2022-02-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owners_name',
            new_name='Name',
        ),
    ]
