# Generated by Django 3.2.11 on 2022-02-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20220202_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
