# Generated by Django 3.2.11 on 2022-01-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marked_price',
        ),
    ]
